## All paths defined in this config file must be either absolute or relative to the 
## location of the Snakefile!
## Scripts are located in the metaWRAP bin/metawrap-modules. Move the modified qc module (read_qc_snakemake.sh) into that directory. 
metatext: path/to/metadata
scripts: path/to/scripts

## ASSEMBLY
##-------------------------------------------------------------------------------------------
## Options- "metaspades" OR "megahit"

assembly: metaspades
##-------------------------------------------------------------------------------------------
##-------------------------------------------------------------------------------------------
## Specify "TRUE" (yes) or "FALSE" (no)

## TOGGLE BLOBOLOGY
##-------------------------------------------------------------------------------------------
blobplot: TRUE

## TOGGLE KRAKEN MODULE
##--------------------------------------------------------------------------------------------
kraken: TRUE

## TOGGLE QUANT_BINS MODULE
##--------------------------------------------------------------------------------------------
salmon: TRUE

## TOGGLE CLASSIFY_BINS MODULE
##--------------------------------------------------------------------------------------------
taxator: TRUE

## TOGGLE ANNOTATE_BINS MODULE
##--------------------------------------------------------------------------------------------
prokka: TRUE

## DEFINE OUTPUT DIRECTORY
##--------------------------------------------------------------------------------------------
output: path/to/output


## Information about the experiment
##--------------------------------------------------------------------------------------------
readlength: 63

## The maximal number of cores to use for metaWRAP modules.
## Note that the actual number of cores available to Snakemake is determined by
## the --cores argument when it is invoked.
ncores: 8 

## Path to a folder containing gzipped fastq files, and the file suffix (typically, either fastq or fq).
## You also need to define the extension distinguishing the two read files.
## <sample-name>_<fqext1>.<fqsuffix>.gz and <sample-name>_<fqext2>.<fqsuffix>.gz.
## Single-end fastq files are currently not supported
##---------------------------------------------------------------------------------------------
input: path/to/input/directory
fqext1: 1
fqext2: 2
fqsuffix: fq
##---------------------------------------------------------------------------------------------


##---------------------------------------------------------------------------------------------
## Path to a folder that will store the output generated by the workflow.
## Additional subfolders of this folder will be generated by the workflow.
## To put output in the current directory, set output to ".".
##---------------------------------------------------------------------------------------------

